spring:
  ai:
    mcp:
      server:
        stdio: true
        name: jenkins-api
        version: 0.0.1
        type: SYNC
  main:
    web-application-type: none
    banner-mode: off
jenkins:
  # jenkins的访问url
  server-uri: ${JENKINS_API_SERVER_URI}
  username: ${JENKINS_API_USERNAME}
  password: ${JENKINS_API_TOKEN}
logging:
  level:
    root: INFO